### ISSUE TITLE
[Feature Request] make Move package manager's git cache thread-safe

### ISSUE THREAD

**Issue by sblackshear** [diem/diem#10102]
### Problem
I ran into an issue when trying to use the package manager in a multithreaded context. Specifically:
- I have some genesis modules w/ git dependencies on the Move stdlib that get built using the Move package manager
- I have two Rust unit tests that each call this build
- The tests are run concurrently and (occasionally, but not consistently) crash the package manager with a `called Result::unwrap() on an Err value: No such file or directory (os error 2)` message or a message about failing to resolve the Move stdlib in the package manager's cache.

I solved my problem by doing the genesis build lazily + only once via a `once_cell` constant, which removes the crashes described above. So this issue is by no means a blocker for me, but it would be nice if the package manager protected you from this by default (especially since it took me awhile to figure out what was going on).

Apologies for not providing a repro, but I think any code that tries to concurrently build a Move package w/ git dependencies should exhibit this problem.

### Proposed solution
I believe `cargo` addresses this by using a file lock to ensure that multiple instances of `cargo` are never running concurrently while touching the file system--this is presumably what the `Blocking waiting for file lock on build directory` message you get while doing two builds at once means. I think a similar solution would work well for the Move package manager.

**Comment by tzakian** [comment]
Closing as this issue should be resolved by https://github.com/diem/move/pull/13
