### ISSUE TITLE
[language] improve functional tests UX

### ISSUE THREAD

**Issue by vgao1996** [diem/diem#1583]
A few outstanding awkwardness of functional tests folks have been experiencing recently:
1) When a checker directive fails, it doesn't tell the user how and why.
2) The current test passing logic is a little bit weird. It requires either
  a) All transactions pass.
  b) The user writes at least one check.
    - This is exactly where things get counterintuitive at times: this rule sheds all responsibilities to the user while giving a false sense that it has some protection against each transaction, which it doesn't.
3) Minor bugs/broken features
  a) The transaction directive is non-existent.
  b) #1475
4) Lack of a tutorial/introductory document.

Plan:
- Instead of using the `filecheck` crate, implement our own checker. 
  - This solves 1) and 2), as it gives full control on source location info, and allows fine tuning our failure condition: we will be able to require all error outputs to be matched against for a test to pass. It also makes it easier to add new directives, which solves 3).
- Well obviously, write a tutorial.

I don't have a timeline for this yet, but I'll try to work on these during my fragmented times or as a relaxation after being focused on some other more intensive projects for a long time.

**Comment by bob-wilson** [comment]
@vgao1996 Is this issue still relevant?

**Comment by vgao1996** [comment]
Closing as a lot of issues are no longer relevant + we're deprecating functional tests
