### ISSUE TITLE
[vm validator] enforcing expiration time

### ISSUE THREAD

**Issue by phoenix-antigravity** [diem/diem#2347]
## Motivation
Transactions have `expiration_time` field
It's used to ensure better service. If current on-chain time is greater than or equal to expiration_time and this transaction has not been included, user can be certain that it will never be included.

Currently we don't enforce any limits on this field. Users can submit transaction with arbitrary expiration times. 
It's also possible to intentionally craft transaction that will stuck in mempool(e.g. with sequence number larger than current one). To address latter issue, mempool enforces global ttl policy (e.g. transaction will be dropped from mempool after 24 hours)

## Pitch
Libra aims to serve real-time payments. There's no known case for transaction with big expiration time
Proposal is to:
* enforce sane expiration time boundaries for user transactions. It'll be done by `vm_validator` check inside of Shared Mempool
* remove separate TTL limit from mempool and keep garbage collection based on transaction expiration time only  

Boundaries themself are expected to be small (around several minutes) and configurable
Config can be stored on-chain and enforced globally or local per node(still subject to discuss)

**Comment by xiaxiangzhou** [comment]
What's the status of this issue? Calibra signing service is depend on this feature.

**Comment by aching** [comment]
The use case for transactions with long expiration times is for pre-signed transactions.  They can still be eliminated from the mempool by obsoleting the sequence number.
