### ISSUE TITLE
[RFC][meta] Notes on Immutability and Reducing Risk of Validator Collusion

### ISSUE THREAD

**Issue by sambarnes** [diem/diem#2741]
## Background
Libra is a permissioned blockchain with a federation of validators/block proposers. The most common argument against such a setup is the possibility of collusion by that authority set. For many users, the (albeit unlikely) ability of validators to coordinate and alter the history of the chain creates a reasonable amount of doubt in the system's immutability — one of the core tenets of blockchain engineers and enthusiasts. Such a situation can, of course, be avoided by using traditional Proof of Work (PoW). For reasons described at length elsewhere, this is not ideal for Libra ["due to their poor performance and high energy (and environmental) costs."](https://github.com/libra/libra/tree/master/consensus#advantages-of-the-hotstuff-paradigm)

## Proposal

So long as some PoW based system exists, however, it is possible for another chain to piggyback on the immutability of that system through "anchoring". For each newly committed block (or set of blocks) in Libra, a transaction is submitted to a sufficiently large PoW chain (e.g. Bitcoin). The transaction's payload contains a cryptographic commitment to those new blocks. Libra validators can continue processing and committing new blocks at the intended throughput, while also achieving a level of immutability comparable to the parent chain.

Anchoring is not intended to be a part of consensus. It is a separate, minimal service that few entities would run along-side normal operation of the Libra protocol as a means of creating an auditable history of the protocol's operation. While any sufficiently trusted PoW chain would suffice, for the sake of simplicity and familiarity, Bitcoin will be used as the primary example moving forward. In theory, this simple scheme is blockchain agnostic and can be applied to any immutable parent ledger with slight modifications to transaction structure.

LibraBFT can be summarized with the following overview taken from the [Libra consensus component README](https://github.com/libra/libra/tree/master/consensus#librabft-overview):
> In LibraBFT, validators receive transactions from clients and share them with each other through a shared mempool protocol. The LibraBFT protocol then proceeds in a sequence of rounds. In each round, a validator takes the role of leader and proposes a block of transactions to extend a certified sequence of blocks (see quorum certificates below) that contain the full previous transaction history. A validator receives the proposed block and checks their voting rules to determine if it should vote for certifying this block. These simple rules ensure the safety of LibraBFT — and their implementation can be cleanly separated and audited. If the validator intends to vote for this block, it executes the block’s transactions speculatively and without external effect. This results in the computation of an authenticator for the database that results from the execution of the block. The validator then sends a signed vote for the block and the database authenticator to the leader. The leader gathers these votes to form a quorum certificate that provides evidence of $\ge$ 2f + 1 votes for this block and broadcasts the quorum certificate to all validators.
> 
> A block is committed when a contiguous 3-chain commit rule is met. A block at round k is committed if it has a quorum certificate and is confirmed by two more blocks and quorum certificates at rounds k + 1 and k + 2. The commit rule eventually allows honest validators to commit a block. LibraBFT guarantees that all honest validators will eventually commit the block (and proceeding sequence of blocks linked from it). Once a sequence of blocks has committed, the state resulting from executing their transactions can be persisted and forms a replicated database.

A single Bitcoin transaction can contain 80 bytes of arbitrary data. Using this space, a Libra anchor can be represented by including a hash of the highest committed Quorum Certificate.

The goal of the anchoring service is to include one transaction in every Bitcoin block, covering all newly produced Libra blocks. This is not to say that every Libra block needs a corresponding anchor, though. For example, an anchor submitted for block 100's QC also implicitly covers blocks 0 through 99 as a QC is already commitment of a state change based on the previous blocks. Thus, we are able to have only one anchor transaction in flight at any given point in time.

```
On creation of a new Bitcoin block:
1) check DB for TX-ID of last submitted anchor transaction
2) query Bitcoin node for it's status:
        transaction does not exist:
            submit new anchor transaction for highest Libra QC
        transaction exists and is still pending:
            perform a "replace-by-fee" for a new anchor transaction using highest Libra QC
        transaction exists and was confirmed:
            resubmit info about the confirmed anchor back into Libra, using a Move resource (if the operator wants to publish their anchors for others)
            submit new anchor transaction for highest Libra QC
3) save the new transaction locally as a pending anchor
```

The ["replace-by-fee"](https://en.bitcoin.it/wiki/Replace_by_fee) strategy will ensure that even in times of high-traffic, we will always be attempting to anchor the most recent Libra block. On the topic of cost, a single anchor per Bitcoin block would run approximately `$0.50 (average tx) * 144 (tx/day) * 365 = $26,280`. This cost could be higher or lower depending on traffic, but regardless, it is negligible compared to the amount of resources being poured into achieving the same level of imutability in Bitcoin PoW.

Surely there are implementation details that would need ironed out. The above description aims to illustrate that it is possible to enhance the immutability of Libra with relatively little technical complexity or financial overhead.

## Thoughts and Future Considerations

**Who would run this?**
As it requires the operator to spend small amounts of BTC per anchor, this would likely be a voluntary effort at first, done as a courtesy to the community. Individuals would reserve the choice to perform their own independent anchoring, of course. Though it is easier and arguably just as effective to continuously audit the anchors produced by another entity that publishes their anchors (on-chain or otherwise). As the Libra ecosystem progresses towards full decentralization — or as the need arises due to consistently high Bitcoin fees — it might make sense to publicly subsidize the creation of anchors, incentivizing their submission or auditing.

**Is one anchor per Bitcoin block necessary?**
No, it doesn't really need to be every block. Aiming to put an anchor in every block simply brings Libra to a level of immutability similar to Bitcoin. It would be worth exploring the right balance, though. Perhaps once every 6 Bitcoin blocks would suffice — only submitting the next anchor when the previous one has hit [6 confirmations](https://en.bitcoin.it/wiki/Confirmation#Number_of_Confirmations).

---

Although implementation is rather trivial and I would be willing to open a PR, I was hoping to hear what others in the community think about the idea before moving forward. My knowledge of the Libra ecosystem is far from complete at this point, and would appreciate any insight into this topic. Has collusion risk has been discussed previously?

**Comment by aching** [comment]
Thanks for this RFC and for sharing your thoughts.  I think you have a lot of good ideas here around additional verification to ensure an immutable blockchain history.  I'd like to add a few comments.  Similar to other blockchains, Libra will have full nodes that verify the history of the chain.  If the validators try to change history, the full nodes will notice and can provide evidence of the attempt to rewrite history.  Full nodes also can re-execute transactions to ensure the correct execution of the transaction history and ensure that the validators are not colluding on arbitrary transaction execution.

Similar to your thinking about anchoring, we have the notion of waypoints (https://github.com/libra/libra/blob/master/tech-papers/lbft-verification/lbft-verification.pdf), an off-chain mechanism for selecting an initial set of validators and and specific point in accumulator history.  It is our hope that these waypoints could be published in trusted sources such as the well known websites as well as embedded in other blockchains as you suggest.

I think that, if it is possible, putting waypoints (or their hashes if they are too big) in other trusted blockchains would be nice service for the community to notify them about any historical forking and build up more trust in the Libra blockchain.

**Comment by aching** [comment]
+ @dmitri-perelman

**Comment by dmitri-perelman** [comment]
Agree with @aching about the role of the FullNodes as "external validators".
The idea of anchoring is interesting. As @aching mentioned above, the waypoints are serving a similar purpose. Putting waypoints on a PoW chain could increase trust in the waypoints (today the trust in a waypoint is based on the trust in Libra Association), so it could be a great idea.

@sambarnes as far as I understand your idea, the upload to a PoW could be done externally. An external observer (e.g., a FullNode, or a special Libra Association service) can periodically upload the hash of the latest LedgerInfo / Waypoint to Bitcoin, s.t. Libra chain would know nothing about it.

**Comment by dahliamalkhi** [comment]
Thanks for the proposal and for the great discussion. 

I totally support the comments already made by @dmitri-perelman and @aching. I would like to emphasize that Libra is a system backed by a reserve and subject to regulation oversight. Hence, the Libra chain is governed by the Libra Association, and the Association has the final authority to determine the state of the chain. This is not like Bitcoin where the users may decide which branch to follow, etc.

@aching and @dmitri-perelman already mentioned Waypoints and Fullnodes. These mechanisms allow the Association to guard and publish the definitive state of the chain.

**Comment by sambarnes** [comment]
@aching Huh, interesting! I have not come across waypoints yet while reading, or must have just missed them. I will have to look into that some more. The way you describe them does make it seem like a useful thing to anchor. Likely much more suitable than QCs, at that.

I do agree that full nodes already serve as "external validators" of sorts, and their operators can certainly cry wolf if they notice that a historical re-org happened. However as @dahliamalkhi mentioned, those full node operators have no real power at the end of the day:

> ... the Libra chain is governed by the Libra Association, and the Association has the final authority to determine the state of the chain. This is not like Bitcoin where the users may decide which branch to follow, etc.

Sure they might have a copy of the old chain-state, but according to who? The Libra Association could (hypothetically) deny that it happened, say it was a bug, and point them towards the real (i.e. newly altered) chain state. The Association could even own up to the historical alteration if the particular instance paints them in a good light with the public. Opening the door for a corrupted organization to control the historical narrative.

Due to regulatory reasons, yes the Association has final say in what the current state of the chain is. Full node operators complaining of historical alterations will just be met with responses of "ehh, too bad". And I'm not saying that is a bad thing, either. Swift and decisive governance is important in a project's growth. After all, the Association has to remain in good standing with _nation states_ if Libra is to succeed globally.

However, the goal of anchoring is not to come to consensus about what the _current state_ of the chain is. The intention is to create an immutable and auditable history of all actions that the Association took to reach that current state (e.g. they progressed along through states A->B->C->D then re-organized to A->B'->C'->D').

I think @dmitri-perelman summarized it perfectly with the following: `"Putting waypoints on a PoW chain could increase trust in the waypoints (today the trust in a waypoint is based on the trust in Libra Association)."` Its not that this mechanism will allow users to choose a fork to follow (at least not in the near-term centralized stages, while Libra remains a PoA-like protocol). Rather, it will allow users to see a history of the manual changes that were made by the Association, whether such events happen frequently, and if said actions warrant a continuation of trust in them as the governing body.

Perhaps just an opinion: It is the governing body's job to determine the current set of rules that the population abides by. It is not a governing body's job to unilaterally dictate what happened in the past to arrive at that current state. Their actions in breaking promises to their constituents (i.e. reverting "immutable" transactions) should be auditable and well-justified. With an immutable history of said actions, corrupt governance would be more easily exposed, while honest and well-intentioned governance would be rewarded with increased trust. Although all of us here trust the Association to act in good faith, I don't believe that is the case for most people when they see a more centralized blockchain with Facebook origins. It may be wise to proactively encourage trust wherever possible.

**Comment by sambarnes** [comment]
> @sambarnes as far as I understand your idea, the upload to a PoW could be done externally. An external observer (e.g., a FullNode, or a special Libra Association service) can periodically upload the hash of the latest LedgerInfo / Waypoint to Bitcoin, s.t. Libra chain would know nothing about it.

And yes @dmitri-perelman that's the idea! Any external observer would reserve the ability to submit anchors to Bitcoin, and the Libra chain doesn't need to know. They also reserve the ability to submit the bitcoin receipts back into Libra (e.g. a Move resource or similar) so that others in the ecosystem have an on-chain index of those anchors, instead of needing to parse all of Bitcoin's transactions looking for matching anchors.

**Comment by aching** [comment]
@sambarnes, thanks for your response. While the Libra Association does determine the state of the Libra blockchain, I think community run full nodes have an important role of blockchain validation.  For example, hopefully in the future, governments or regulatory bodies could begin running full nodes to validate blockchain updates from the validators.  The Libra Association is subject to regulatory oversight and if regulators discover a violation of the protocol they could coordinate a resolution with the Libra Association.  Additionally, if community operated full nodes expose irregular activity, they could present the evidence to governments or regulatory bodies that could trigger a similar process of resolution.  Finally, if the community found strong evidence of foul play from the validators or the Libra Association via full nodes, they also could simply share the proof publicly and convince the world about the issue - and rightfully question the trustworthiness of the Libra Association.  The existence of these public safeguards (that anyone can verify with a full node) are important to building trust in the Libra Association and its blockchain.

As you suggest, embedding waypoints in other blockchains would be another great way to provide evidence of misbehavior.

**Comment by earonesty** [comment]
@aching while regulatory actions can result in funds reversal, that reversal should, too, be recorded on-chain.  in other words: in no circumstances should *history* be revised, therefore a community-trusted waypoint seems quite reasonable.
