### ISSUE TITLE
[move-prover][Bug] Move Prover has a footgun with "spec fun <function name>"

### ISSUE THREAD

**Issue by DavidLDill** [diem/diem#3227]
# 🐛 Bug
This is really just a small foot-gun that I ran into.  However, this is the kind of error we especially don't want users of the Move Prover to make.  This is a surprisingly easy error to make when cutting and pasting:

If:
1. You have several functions, and
2. you give later spec block of one function the name of another function (redundantly), probably because of a cut-and-paste error, and
3. all variables mentioned in the mis-named spec block have compatible names and types for the function the user meant to associate it with, and
4. the function with the name matching the mis-named spec block does not have an error, or has an identical error with the function the user meant to associate it with

then, the prover may not detect an error that the user thought it would catch, because there is  no spec for a function the user thought he was specifying.

This is really a usability problem with syntax.  I'm using a convention where I put spec blocks for functions right after the function, and the name of the spec block is just extra typing for me.  I think we considered the option of not naming spec fun blocks.  (I believe I thought putting the function name in there was a good idea when we were discussing it.)

## To reproduce

**Code snippet to reproduce**
```rust

// dep: tests/sources/stdlib/modules/hash.move

module SpecMissedError {
    // The prover only reports an error for f1, even though f2 has the same error.
    // if the spec block for f2 is named "spec fun f2" instead of "spec fun f1", it 
    // produces the expected results
    fun f1(v: u64): u64
    {
       v
    }
    spec fun f1 {
       ensures result != v;
    }
    fun f2(v: u64): u64
    {
       v
    }
    spec fun f1 {
       ensures result != v;
    }
}

```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by wrwg** [comment]
Move sources are generally position independent, so doing an association via position in the source would be not confirming to the language design. Moreover, the option to move the specs out of the way is a feature by itself.

Would it help if we allow only one spec block per function?
