### ISSUE TITLE
[RFC][Docker] cache toolchain layer and publish it to Dockerhub

### ISSUE THREAD

**Issue by sausagee** [diem/diem#3475]
[Why]
In the last few weeks, we have seen frequent build outages to due to sporadic issue in 3rd party hosting, such as crates.io and googleapis.com.  

Continuous Push on devnet was hammered hard by such issue this week.  Retry logic was added to the docker build script. However, it seems like pure retrying is ineffective.  <img width="1311" alt="image" src="https://user-images.githubusercontent.com/7528420/79482005-1244b900-7fc5-11ea-92f3-b9879124f7df.png">

[What]
Build and cache the toolchain layer locally (ECR as well) and publish it to Dockerhub.  The toolchain layer includes
- rust toolchain
- crate cache
- 3rd party tools
- compiled deps cache (post-MVP)

**Comment by sausagee** [comment]
@rexhoffman I think this is no longer needed after your recent change in `build_environment` image. Feel free to close it.

**Comment by rexhoffman** [comment]
Closing.

**Comment by rexhoffman** [comment]
Ehh... we could still use a crate cache.

**Comment by rexhoffman** [comment]
been done for a while in two cis.
