### ISSUE TITLE
[storage] Backup & Restore

### ISSUE THREAD

**Issue by msmouse** [diem/diem#3737]
# LibraDB Data Backup Specification

https://github.com/libra/libra/blob/master/specifications/db_backup/spec.md

### Incremental State Backup

With only transactions and state snapshots backed up, to recreate state at arbitrary version in between snapshots we need to reply transactions on top of "base" snapshot. It has the drawback of 1. consuming unnecessary compute power; 2. requiring dependency on LibraVM/Executor, and which can not only run the latest Libra protocol but also old transactions & modules that potentially outdate recent Libra upgrades.

We can overcome this by storing backing up WriteSets or even account blob binary diffs on a per transaction basis. With proper indexing, we can easily answer per account historical state inquiries without replaying all transactions on top of the base snapshot, although it's hard to provide cryptographic proof of the answer.

With proper caching (to cover the performance drawback), we can even store binary diffs directly as state tree leaves (even internal nodes, which represent a larger saving disk space wise), with occasional blob snapshots attached, making the data structure "diff native", saving storage space further, though the tradeoffs demand to be better thought out definitely.

## Action Items
* [x] implement FsBackupStorage as a direct implementor of `trait BackupStorage`
* [x] implement S3BackupStorage as a seperate command line tool and create CommandBasedBackupStorage adaptor
* [x] implement BackupService and BackupController
* [x] implement RestoreController.
* [x] Add tests to partial DB behavior
* [ ] add regression test to guarantee a backup in current protocol can be recovered.
* [ ] accommodate LedgerCounters to the workflow
* [ ] invoke backup in action with cron on one of the testnet validators
* [x] epoch change ledger info backup, as root of trust
* [x] transaction backup, and ability to optionally skip running transactions when restoring
* [ ] potentially, adaptor to use a live peer node as a backup store (popping up db from a running node)
* [ ] add compression/decompression filters to the storage
* [ ] realtime transaction backup
* [ ] (realtime) incremental state backup
* [ ] state snapshot + incremental state backup merging tool

**Comment by zmanian** [comment]
I notice that state snapshots are incrementally verifiable.

We implemented an instant sync feature in Tendermint recently that combines a light client for verified commits without running the transactions and incrementally verifiable snapshots.

https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-042-state-sync.md

Seems like the proposed back up strategy heads in that direction.
