### ISSUE TITLE
[Bug] Issue in quantifying $Value

### ISSUE THREAD

**Issue by junkil-park** [diem/diem#4648]
# 🐛 Bug

Prover doesn't prove an existentially quantified statement which quantifies over `$Value` and use it to index a vector, although it works well if the quantified variable has the type of `int`.

## To reproduce

**Code snippet to reproduce**
```
public fun push_one(v: &mut vector<u64>) {
    Vector::push_back(v, 1);
}
spec fun push_one {
    ensures exists i in 0..len(v): v[i] == 1; // proved
    ensures exists i: u64 : v[i] == 1; // FIXME: not proved, but should be
```
(This example can be found in `tests/sources/functional/exists_in_vector.move`.)

Prover can prove the first postcondition above, which is translated to `... exists i: int :: ...` in Boogie.

However, the second postcondition is weaker than the first one, but *not proved*. Note that this one is translated into `... exists i: $Value :: $IsValidU64(i) ...`.

**Stack trace/error message**
```
error: post-condition does not hold

    ┌── exists_in_vector.move:27:9 ───
    │
 27 │         ensures exists i: u64 : v[i] == 1; // not working
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    │
    =     at exists_in_vector.move:16:5: push_one (entry)
    =     at exists_in_vector.move:17:17: push_one
    =         v =
    =           vector{
    =             (size): 8857,
    =             1: 18446744073709551006,
    =             default: undef}
    =     at exists_in_vector.move:16:5: push_one (exit)
    =         result =
    =           vector{
    =             (size): 8858,
    =             1: 18446744073709551006,
    =             8857: 1,
    =             default: undef}

Error: exiting with boogie verification errors
```

## Expected Behavior

Prover should prove the second postcondition as well.

**Comment by junkil-park** [comment]
This issue can be solved by enabling the following flags: `cargo run -- -d ../../../../stdlib/modules --verbose debug exists_in_vector.move -C=backend.serialize_bound=0 -C=backend.use_array_theory=true -C=backend.boogie_flags=[\"/proverOpt:O:smt.array.extensional=false\",\"/proverOpt:O:smt.mbqi=true\"]`

However, any fix was not submitted yet because we need to first examine the consequence about adding some of those as the default option.

**Comment by wrwg** [comment]
This problem is pervasive and needs invetigation

**Comment by wrwg** [comment]
Fixed with monomorphization.
