### ISSUE TITLE
[Feature Request] Add an explicit "iff" operator (<==>) to the specification language

### ISSUE THREAD

**Issue by DavidLDill** [diem/diem#4977]
# 🚀 Feature Request

An new operator <==> for equality on Booleans only.  It should have similar precedence as ==>.
Since people probably don't have clear expectations for the relative precedence of ==> and <==>,
we should forbid consecutive uses of <==> and ==> (require explicit parenthesization).

== should continue to work on Booleans so that code with generic types can use ==.

## Motivation
I thought we didn't need an "iff" operator for Boolean expressions because it's the same as equality (==).

Unfortunately, we want different == than for <==>.  For example:
x == P && Q  parses as (x == P) && Q, which is what we want of x and P are numbers.
If P and Q are predicates and the user is trying to get "iff", because user are used to 
&& binding more tightly than ==> or <==>, i.e. x == (P && Q) 

x <==> P && Q would be expected to parse as x <==> (P && Q).

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by wrwg** [comment]
Here are some pointers how to implement this feature. The general advice is to follow the example of how the already existing "implies" operator is implemented.

Changes to the move compiler (./language/move-lang).

- Add the new token to the [lexer](https://github.com/diem/diem/blob/main/language/move-lang/src/parser/lexer.rs).
- Add a new [BinOp_](https://github.com/diem/diem/blob/main/language/move-lang/src/parser/ast.rs#L486) variant to the abstract syntax tree.
- Extend the parser in [syntax.rs](https://github.com/diem/diem/blob/main/language/move-lang/src/parser/syntax.rs) to parse the new operator with the right binding priority. Priority should be lower than &&/||. 
- Check how the Implies operator is handled; it is only allowed in specification language mode.

Changes to the move model (./language/move-model):

- Introduce new operator in the [model/prover AST](https://github.com/diem/diem/blob/main/language/move-model/src/ast.rs#L742)
- Introduce a new [binary bultin operation](https://github.com/diem/diem/blob/main/language/move-model/src/builder/spec_builtins.rs#L77) for it.

Changes to move prover (./language/move-prover):

- Extend boogie backen's [spec_translator](https://github.com/diem/diem/blob/main/language/move-prover/boogie-backend/src/spec_translator.rs#L698) to handle new operator.
- Add a test case in move-prover/tests/sources/functional.


@Checkmate50
