### ISSUE TITLE
[logging] Kibana Usage Tutorial

### ISSUE THREAD

**Issue by gregnazario** [diem/diem#5445]
### Overview
Kibana is hard to use for n00bs.  So, let's make a simple context based tutorial with the actual elasticsearch cluster for users.

#### Expected topics
- [x] Navigating between search and management
- [ ] Understanding the indices
- [x] Making a search query, and basic syntax for the query language
- [x] Filtering using the already indexed fields
- [x] Showing limited amounts of fields e.g. simple log view
- [x] Creating Tables
- [ ] Creating plots
- [ ] Dashboarding
- [ ] Alarming

#### Nice to haves
1. How to use the in browser query (for things like _count)
2. Advanced topics on how to use the query language not in the search bar

### Related Issues
Parent Issue: https://github.com/libra/libra/issues/5441

**Comment by gregnazario** [comment]
In progress doc: https://docs.google.com/document/d/1r_YTlG3hviVcTiHxWrlOtXMNSsG06kRQtA-Yip2CRZU/edit?usp=sharing

1. Visualization
2. Understand indices and the limitations around them

**Comment by AnomalRoil** [comment]
Thanks, as a n00b working on the security logging, this is going to be useful to me

**Comment by gregnazario** [comment]
I won't be doing any more work on this tutorial, but hopefully it's now helpful https://github.com/diem/operator-runbooks/blob/main/tutorials/kibana.md
