### ISSUE TITLE
[logging] Prevent deduplicated log lines

### ISSUE THREAD

**Issue by gregnazario** [diem/diem#5569]
### Overview
Logs if retransmitted will have different `_id`s and could be duplicated.  Providing a `_id` for each document that is unique, will ensure that log messages are not overwritten or repeated.

### Solution
In order to prevent duplication, we either need to add a unique id before transmission retries.  We have a couple options:
* Make a UUID put that in the original JSON log
* Use Logstash fingerprinting to hash the contents to generate ID https://www.elastic.co/guide/en/logstash/current/plugins-filters-fingerprint.html

### Related Issues
Parent Issue: https://github.com/libra/libra/issues/5441

**Comment by gregnazario** [comment]
ID change https://github.com/libra/libra/pull/5619

There will need to be a change to logstash afterwards

**Comment by gregnazario** [comment]
@sherry-x Does this have to be redone for vector?  Duplicated logs shouldn't happen very often, but it can cause confusion, which is why I prioritized this.

**Comment by sherry-x** [comment]
Yes, if we need this we will have to redo this on vector here https://github.com/libra/partners/blob/master/validator/helm/files/vector.toml

**Comment by gregnazario** [comment]
since this is owned by the association, I'm just going to close this issue.  it's low likelyhood and low impact
