### ISSUE TITLE
[Bug] "Modifies" with bad generic type causes a panic.

### ISSUE THREAD

**Issue by DavidLDill** [diem/diem#5736]
# 🐛 Bug

In PR #5664: LibraConfig.move, I included an erroneous spec:
       modifies global<Config>(CoreAddresses::LIBRA_ROOT_ADDRESS());

instead of the correct spec:
       modifies global<LibraConfig<Config>>(CoreAddresses::LIBRA_ROOT_ADDRESS());

"Config" is a generic parameter name.  This caused a panic.

Here is a partial stack trace:
        // 7: 0x10dd2413e - spec_lang::ty::Type::require_struct::ha827918002d1e7a3
        // 8: 0x10d6da2a3 - move_prover::spec_translator::SpecTranslator::translate_resource_exists::{{closure}}::h11aebacab7e9def9
        // 9: 0x10d6d8686 - move_prover::spec_translator::SpecTranslator::trace_value::h759ea6a30a807401
        // 10:0x10d6c72ac - move_prover::spec_translator::SpecTranslator::translate_resource_exists::hceb687f604489eca

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by wrwg** [comment]
Need to verify whether this is still an issue
