### ISSUE TITLE
[Bug][Move prover] Spec language models structs as empty, but instruction adds a dummy field

### ISSUE THREAD

**Issue by DavidLDill** [diem/diem#5738]
# 🐛 Bug

For some reason, Move adds a "dummy" field to empty structs.  The translation of the spec language doesn't know about this, so specs such as the one on LibraConifg.move:160 in PR #5664 erroneously report errors.

LibraConfig::publish_new_config_and_get_capability last line (return value):
           ModifyConfigCapability<Config> {}

Failing spec: ensures result == ModifyConfigCapability<Config> {};

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by wrwg** [comment]
This error is likely on Boogie level and should be fixed.

**Comment by wrwg** [comment]
This has been fixed a while ago.
