### ISSUE TITLE
[Bug] DEFAULT_OUTPUT_DIR may be inaccessible in interface generator

### ISSUE THREAD

**Issue by guangyuz** [diem/diem#6263]
# 🐛 Bug

When calling move_compile_no_report(x, x, x, None), command_line::DEFAULT_OUTPUT_DIR is used to save interface files. However this dir may be inaccessible in some cases, for example the user has no write permission to it.

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by guangyuz** [comment]
A patch has been submitted - https://github.com/libra/libra/pull/6262

**Comment by tnowacki** [comment]
> However this dir may be inaccessible in some cases, for example the user has no write permission to it.

The compiler needs to be able to write to output directories. 
This directly in particular can be specified by `--out-dir` in both move-check and move-build. 

What is your workflow that you have problems with?

**Comment by guangyuz** [comment]
Ok, I see. My test environment has a different configuration from libra.org. When I run the cargo test, the case sanity_check_testsuite will try to create the directory move_build_output under language/move-lang. Since my environment is write-protected on the source code directory, the test will fail. Therefore, this is not a problem, and I will close the bug.

**Comment by bob-wilson** [comment]
If it really doesn't work to run the tests when using read-only source directories, that sounds like a problem we should fix.

**Comment by tnowacki** [comment]
Any suggestions @bob-wilson? 

The compiler needs to be able to write somewhere...

**Comment by tnowacki** [comment]
Is there any sort of virtual file library for Rust? If we could just keep it in memory or something that might work. But the tempdir thing has blown up on me before

**Comment by bob-wilson** [comment]
> Any suggestions @bob-wilson?
> 
> The compiler needs to be able to write somewhere...

I don't have a quick fix, but this issue seems like it can wait a while.... Some thoughts:

- Clang manages its own module cache (see https://clang.llvm.org/docs/Modules.html#compilation-model) but that could be a lot of work
- Generally I lean toward making these things explicit, e.g., require the user to specify a location when using interface files. Then the build system can manage the files instead of having the compiler guess.

**Comment by tnowacki** [comment]
> Generally I lean toward making these things explicit, e.g., require the user to specify a location when using interface files. Then the build system can manage the files instead of having the compiler guess.

That's effectively whats going on right now. If we had a build system, I'd say we'd configure this with some path/env variable magicry without pissing anyone off, but without it, I feel we are stuck in a world of defaults

**Comment by tnowacki** [comment]
> Clang manages its own module cache (see https://clang.llvm.org/docs/Modules.html#compilation-model) but that could be a lot of work

I feel like this is a bit different as its for source level errors, not for the binaries (but I could be misunderstanding what clang is using this for).

In general, I would always consciously choose actual files for debug-ability. It is very hard (impossible) to debug against in memory artifacts

**Comment by bob-wilson** [comment]
Clang's module cache holds binary files constructed automatically from header files (basically precompiled headers). It's very similar to what we're doing here with interface files.
