### ISSUE TITLE
[libra framework] Example of why the hot potato resource type is needed

### ISSUE THREAD

**Issue by junkil-park** [diem/diem#6461]
One of the access control requirement is that only TC can have MintCapability

The following spec (in the Diem module) tries to specify the requirement:
```
/// In order to successfully call `mint` and `mint_with_capability`, MintCapability is
/// required. MintCapability must be only granted to a TreasuryCompliance account [[H1]][PERMISSION].
/// Only `register_SCS_currency` creates MintCapability, which must abort if the account
/// does not have the TreasuryCompliance role [[H1]][PERMISSION].
apply PreserveMintCapAbsence<CoinType> to *<CoinType> except register_SCS_currency<CoinType>;
apply Roles::AbortsIfNotTreasuryCompliance{account: tc_account} to register_SCS_currency<CoinType>;
```

This spec ensures that only TC can have the MintCapability which is published at the top-level. However this does not ensure that anyone other than TC owns/uses MintCapability inside of an other struct (not at the top-level but at a lower level). There is no way to specify the latter. More specifically, there can be two possible scenarios:
  - a function (possibly in an other module) obtains a MintCapability from `register_currency`, and
    (1) uses the MintCapability for minting without publishing it, and/or
    (2) stashes the MintCapability inside of an other struct in the global memory (The LBR module is currently doing this).

**Comment by wrwg** [comment]
Should use new abilities for this.

@tnowacki
