### ISSUE TITLE
[move] Allow reserved words to be used in some contexts

### ISSUE THREAD

**Issue by metajack** [diem/diem#6555]
# 🚀 Feature Request

`address` and `signer` are both reserved in Move but extremely common, especially in smart contract code. It would be nice if they would not be forbidden in all contexts.

Example:

```
let address = x"dd";
```

is illegal, but unambiguous that address is a variable name.

**Comment by modocache** [comment]
Thanks for the report! This issue has been resolved since it was posted (I won't dig into the exact commit), now both `signer` and `address` are contextually interpreted as either a keyword or as an identifier.
