### ISSUE TITLE
[Bug][move-prover] Uninformative error message when BOOGIE_EXE is not defined

### ISSUE THREAD

**Issue by DavidLDill** [diem/diem#6589]
# 🐛 Bug

This is not a high-priority bug, but worth fixing eventually for usability.

If BOOGIE_EXE is not set, the Move prover generates a "file not found" error and hangs.  Since it doesn't give the missing file path, it's difficult for a user to figure out what went wrong.  With "mvp -v debug ..." I eventually saw the problem was an incomplete Boogie command line.

The "file not found" problem is a deficiency of Rust libraries, in my opinion.  However, we should deal with this issue, eventually.

Possible solutions (maybe we should do both):
1.  Is there a way to capture errors from commands invoked in from Command::run?  Since Boogie can have a lot of different errors, this might make other problems easier to fine.  Alternatively, if we can't do that and "run" fails, perhaps we can advise the user to run Boogie from the command line.

2. We can check that BOOGIE_EXE, etc. are defined before calling "run" (either in prover_task_runner.rs or earlier).

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by wrwg** [comment]
This is in fact a side-effect of the parallel task execution of Boogie, which has been turned off because of this.

@wrwg thinks he has fixed this.

**Comment by wrwg** [comment]
This has been fixed a while ago.
