### ISSUE TITLE
[Bug] The url is missing in the sample code curl

### ISSUE THREAD

**Issue by toshirot** [diem/diem#6887]
# 🐛 Bug

at https://github.com/diem/diem/blob/master/json-rpc/docs/method_get_account_transactions.md

The url is missing in the sample code curl

curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"get_account_transactions","params":["c1fda0ec67c1b87bfb9e883e2080e530", 0, 100, false],"id":1}'

For example, this is correct　

curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"get_account_transactions","params":["3be5596596c8970b183d91dffd0a9bb3", 0, 100, false],"id":1}' https://testnet.diem.com/v1

**Comment by ericnakagawa** [comment]
Closed by PR #7490

**Comment by ericnakagawa** [comment]
Thanks for reporting the issue @toshirot!
