### ISSUE TITLE
Potential issue for EmptyReader

### ISSUE THREAD

**Issue by dragonboy1994** [diem/diem#6998]
In storage::diemdb::src::event_store::mod.rs, it is mentioned that the `fn get(&self, _position: Position)` for `EmptyReader` is never called. However, when `EmptyAccumulator::append(&EmptyReader, 0, &event_hashes)?` is called in `pub fn put_events( &self, version: u64, events: &[ContractEvent], cs: &mut ChangeSet,)`, then, `fn get(&self, _position: Position)` gets called in `MerkleAccumulatorView::append(&self, new_leaves: &[HashValue])`. 

Won't this lead to a panic!?

**Comment by lightmark** [comment]
@dragonboy1994 Hi, this `EmptyAccumulator` is for one-time accumulator construction so get would not be called. AFAIK, `get` will only be called if you append to a non-empty accumulator. But in our case, we append to an empty accu and then never call `append` to it again so it shouldn't be panic. 

If you have any other questions feel free to reopen the issue.
