### ISSUE TITLE
[Bug] parse_type_tag return error when struct name contains underscore

### ISSUE THREAD

**Issue by jolestar** [diem/diem#7151]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies

#[test]
fn test_parse_tag() {
    let struct_tag_str = "0x1::M::S_";
    let type_tag = parse_type_tag(struct_tag_str);
    assert!(type_tag.is_ok());
}

```

**Stack trace/error message**
```
`Err` value: unrecognized token
```

## Expected Behavior

`S_` is a valid identity, expect parse_type_tag to return ok or let S_ invalid as an Identity. It affects the Identity's Arbitrary and TyptTag's Arbitrary.

## System information

**Please complete the following information:**
- 
- 
-

**Comment by sblackshear** [comment]
Thanks for reporting this!
