### ISSUE TITLE
[Bug] "Unable to get currency info for Coin1 when converting to on-chain"

### ISSUE THREAD

**Issue by javaservlets** [diem/diem#7368]
# 🐛 Bug

## To reproduce
1. build diemcore
2. run examples from https://developers.diem.com/docs/core/my-first-transaction
3. note that you can not proceed after the step "account mint 0 110 Coin1" since you'll get:
==> [ERROR] Error transferring coins from faucet: Unable to get currency info for Coin1 when converting to on-chain units

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
[ERROR] Error transferring coins from faucet: Unable to get currency info for Coin1 when converting to on-chain units
// Paste the output here
```

## Expected Behavior

<!-- A clear and concise description of what you expected to happen. -->

## System information

**Please complete the following information:**
- <!-- Diem Version --> git clone 1/23/21
- <!-- Rust Version -->
- <!-- Computer OS --> macos 11


## Additional context

Add any other context about the problem here.

**Comment by nishant1307** [comment]
Please try using **XUS** instead of **Coin1**

**Comment by bob-wilson** [comment]
That document was previously left using "Coin1" because it has instructions for using testnet. Testnet now has the new currency codes, so I think we can get the docs updated.

@JoelMarcey Who should this go to?

**Comment by JoelMarcey** [comment]
@nimishamw You are updating first transaction for other things already, right? Can this be added to those changes?
