### ISSUE TITLE
[Bug][move compiler] panick: assertion failed: ty_args.len() == constraints.len() at core.rs:1135:5

### ISSUE THREAD

**Issue by rvantonder** [diem/diem#7384]
# 🐛 Bug

Hi! This program causes a panick in `move-build`:

```rust
module M {
    struct S {}
    struct Box<T1, T2, T3> {}

    fun cpy<C: copyable>(c: C) {}

    fun t3<U, C: copyable>() {
        cpy(Box<U, U> {});
    }
}
```

with

```
thread 'main' panicked at 'assertion failed: ty_args.len() == constraints.len()', language/move-lang/src/typing/core.rs:1135:5
```

## To reproduce

Shell command:

```bash
cat <<EOF > /tmp/crash.move && move-build /tmp/crash.move
module M {
    struct S {}
    struct Box<T1, T2, T3> {}

    fun cpy<C: copyable>(c: C) {}

    fun t3<U, C: copyable>() {
        cpy(Box<U, U> {});
    }
}
EOF
```

**Stack trace/error message**

<details>
<summary><b>click to expand trace</b></summary>

```
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:505
   1: move_lang::typing::core::instantiate_type_args
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/typing/core.rs:1135
   2: move_lang::typing::core::instantiate_apply
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/typing/core.rs:1119
   3: move_lang::typing::core::make_struct_type
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/typing/core.rs:552
   4: move_lang::typing::translate::exp_inner
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/typing/translate.rs:1127
   5: move_lang::typing::translate::exp_::exp_loop
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/typing/translate.rs:903
   6: move_lang::typing::translate::exp_
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/typing/translate.rs:912
   7: move_lang::typing::translate::exp_vec::{{closure}}
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/typing/translate.rs:771
   8: core::iter::adapters::map_fold::{{closure}}
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/adapters/mod.rs:905
   9: core::iter::traits::iterator::Iterator::fold
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/traits/iterator.rs:2023
  10: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/adapters/mod.rs:945
  11: core::iter::traits::iterator::Iterator::for_each
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/traits/iterator.rs:678
  12: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/vec.rs:2378
  13: <alloc::vec::Vec<T> as alloc::vec::SpecFromIterNested<T,I>>::from_iter
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/vec.rs:2152
  14: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/vec.rs:2267
  15: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/vec.rs:2002
  16: core::iter::traits::iterator::Iterator::collect
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/traits/iterator.rs:1670
  ...
```

</details>

## Expected Behavior

No panick/crash, probably want to raise a friendlier compile error message?

## System information

**Please complete the following information:**
- Diem Version: master @ ed132a8516aa5ff84298efcf1f119971509ea8d4
- rustc 1.48.0 (7eac88abb 2020-11-16)
- Ubuntu 18.04.5 LTS

## Additional context

Found as part of a compiler fuzzing project that mutates programs: https://github.com/agroce/afl-compiler-fuzzer and https://github.com/comby-tools/comby-mutation-server.

Also hi @sblackshear 👋

**Comment by sblackshear** [comment]
Hi @rvantonder and great to hear from you, it's been too long! I have been admiring your work on comby from afar, very cool stuff.

Thanks for these reports, this afl + comby mix looks very powerful. We should look into incorporating it into our fuzzing CI at some point. Couple of questions for you:

- Does this mean that you have a Comby parser for Move source? I didn't see Move in the list [here](https://comby.dev/docs/overview), but if there is one I would like to play around with some comby-powered refactorings...
- Similarly, are there any Move-specific transformations that are not already in the `comby-mutation-server` repo?

**Comment by tnowacki** [comment]
Fixed in #7401

**Comment by tnowacki** [comment]
As @sblackshear has a conversation going here, leaving for him to close when he wants to :)

**Comment by rvantonder** [comment]
> Does this mean that you have a Comby parser for Move source?

I'll add it in the next release and hopefully done by next week :-) Until then you can use this [custom definition](https://comby.dev/docs/advanced-usage#custom-language-definitions)

```json
{
   "user_defined_delimiters":[
      [ "(", ")" ],
      [ "{", "}" ],
      [ "[", "]" ]
   ],
   "escapable_string_literals":{
      "delimiters":[ "\"" ],
      "escape_character":"\\"
   },
   "raw_string_literals": [],
   "comments":[
      [ "Nested_multiline", "/*", "*/" ],
      [ "Until_newline", "//" ]
   ]
}
```

>  any Move-specific transformations?

In fact, no, nothing overly Move-specific yet: these are fairly generic transformations that duplicate/swap/nest/unnest various block and expression constructs.  Some of the transformations in the example rules file are [specific to Solidity](https://github.com/comby-tools/comby-mutation-server/blob/master/rules/rvt-mutations.toml#L140-L167) for example. Definitely something I can tune when I have a bit more time (I only got the fuzzing working the night before reporting these). 

There's also some templating being thrown into the mix for the corpus, so once I have a chance I'll write up or blog a step-by-step to play with. Happy to follow up on email with more details too.
