### ISSUE TITLE
[Bug] incomplete reasoning regarding existential quantification

### ISSUE THREAD

**Issue by junkil-park** [diem/diem#7435]
This is a completeness issue rather than a soundness issue. Sometimes, Prover fails to prove some true statements that has an existential quantifier. The boogie flag `/proverOpt:O:smt.mbqi=true` may solve this issue, but Prover currently does not turn on this flag by default because it is sometimes costly. The same issue with a different example has been already reported here (https://github.com/diem/diem/issues/4662).

Prover can prover this:
```
public fun push_two(v: &mut vector<u64>) {
    Vector::push_back(v, 1);
    Vector::push_back(v, 2);
}
spec fun push_two {
    ensures exists i in 0..len(v): v[i] == 2;
}
```

However, Prover cannot prove this:
```
public fun push_two(v: &mut vector<u64>) {
    Vector::push_back(v, 1);
    Vector::push_back(v, 2);
}
spec fun push_two {
    ensures exists i in 0..len(v): v[i] == 1;
}
```
It generates the following (false negative) error message:
```
error: post-condition does not hold

    ┌── exists_in_vector.move:83:5 ───
    │
 83 │     ensures exists i in 0..len(v): v[i] == 1;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    │
    =     at exists_in_vector.move:78:1: push_two
    =         v = vector{(size): 18467, default: 2},
    =         result = vector{(size): 18469, 18468: 2, default: 2}
    =     at exists_in_vector.move:79:13: push_two
    =     at exists_in_vector.move:80:13: push_two

Error: exiting with boogie verification errors
```

If we provide the additional statement `ensures v[len(v)-2] == 1;` (to serve as a helping lemma), Prover can prove it:
```
public fun push_two(v: &mut vector<u64>) {
    Vector::push_back(v, 1);
    Vector::push_back(v, 2);
}
spec fun push_two {
    ensures v[len(v)-2] == 1;
    ensures exists i in 0..len(v): v[i] == 1;
}
```

(This issue seems to happen not only to $Vector but also to $ValueArray in Boogie.)

**Comment by wrwg** [comment]
In general, exists should be working better after monomorphization, but complete support is not possible because of SMT restrictions. Closing.
