### ISSUE TITLE
[mempool] Perf regression with CT burst mode

### ISSUE THREAD

**Issue by zihao-c** [diem/diem#7577]
# 🐛 Bug

if we enable burst mode in CT, CT will do keep submitting txs without waiting commit succeed. This over submitting behavior triggered unusual behavior of mempool, which we can see a deep perf regression.

Command to run tests

**with burst mode, duration 4mins:**
```
./scripts/cti --master --run bench --burst
```
dashboard:
http://grafana.ct-1-k8s-testnet.aws.hlw3truzy4ls.com/d/performance/performance?orgId=1&from=1612887437000&to=1612888257000
http://grafana.ct-1-k8s-testnet.aws.hlw3truzy4ls.com/dashboard/new?panelId=2&edit&fullscreen&orgId=1&from=now-30m&to=now

**with burst mode, duration 10mins:**
```
./scripts/cti --master --run bench --burst -- --duration 600
```
dashboard:
http://grafana.ct-1-k8s-testnet.aws.hlw3truzy4ls.com/d/performance/performance?orgId=1&from=1612888759000&to=1612889892000
http://grafana.ct-1-k8s-testnet.aws.hlw3truzy4ls.com/dashboard/new?panelId=2&edit&fullscreen&orgId=1&from=now-30m&to=now

**normal mode without --burst, duration 4mins:**
```
./scripts/cti --master --run bench
```
dashboard:
http://grafana.ct-2-k8s-testnet.aws.hlw3truzy4ls.com/d/performance/performance?orgId=1&from=1612466565000&to=1612467237000
http://grafana.ct-2-k8s-testnet.aws.hlw3truzy4ls.com/dashboard/new?panelId=2&edit&fullscreen&orgId=1&from=1612466565000&to=1612467300000

Observed points:
1. From normal mode, we can see it does have a constant slope of committed txn, but burst mode always stops committing around 1min 30secs no matter how long of the duration
2. Normal mode 4 mins duration can totally commit more than 200k txn, but burst mode can only make max around 40k txn no matter how long of the duration

Normal mode, 4 mins
![image](https://user-images.githubusercontent.com/6146503/107400849-18a5a380-6ab7-11eb-9093-50adc2686571.png)
Burst mode, 4mins
![image](https://user-images.githubusercontent.com/6146503/107400949-3541db80-6ab7-11eb-897d-5c1b09134346.png)
Burst mode, 10mins
![image](https://user-images.githubusercontent.com/6146503/107400976-3ecb4380-6ab7-11eb-8809-d17acf6a0d6e.png)

@davidiw @zekun000 

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by davidiw** [comment]
Oh wow, so this becomes entirely choked?

**Comment by snakech** [comment]
> Oh wow, so this becomes entirely choked?

seems yes

**Comment by zekun000** [comment]
it's fun that validator mempool are empty but fullnode all have 15k

**Comment by JoshLind** [comment]
Thanks for flagging @snakech. Would it be possible to provide links to the logs? I have a few suspicions around the mempool code and hopefully the logs will shed some more light here.

**Comment by snakech** [comment]
> Thanks for flagging @snakech. Would it be possible to provide links to the logs? I have a few suspicions around the mempool code and hopefully the logs will shed some more light here.
> 
> @zekun, one of my suspicions is around the notifications between consensus and mempool (e.g., when consensus pulls transactions from mempool). For example, if you compare the graphs of a normal run vs. a burst one, you can see:
> 
> * consensus event loop idle percent is much higher (which suggests mempool has flopped, not consensus)
> * looking at the "pull txn" graph, the response time spikes and then there's no more data. Perhaps we're hitting a timeout, e.g., here? https://github.com/diem/diem/blob/5f5f317f4591311a28439a57a44ad684b0a74112/consensus/src/txn_manager.rs#L63
> 
> Anyway, logs should definitely help here.
will redo the test and post the logs there

**Comment by snakech** [comment]
http://kibana.ct-2-k8s-testnet.aws.hlw3truzy4ls.com/app/kibana#/discover?_g=(time:(from:'2021-02-11T16:49:36Z',to:'2021-02-11T17:00:15Z'))

Log is updated for 4 mins burst test

**Comment by zihao-c** [comment]
```looked through the txn generation, it basically sends txns with incremental seq num without waiting for commit
11:38
so the it’s possible that one txn with seqnum X expired before committed (the expiration is 50s) resulting all the subsequent txns to never be ready``` by @zekun000, thx for your find. 


fully explanation here: https://toroeng.slack.com/archives/G01MAKL02UX
