### ISSUE TITLE
[Feature Request] Support for `index_of` in the Move specification language

### ISSUE THREAD

**Issue by tzakian** [diem/diem#7615]
Today we can't get the index of a matching element in a vector in the Move specification language.

This is an issue in the specification for concurrent preburns -- in particular I want to write an ensures condition that says the preburn queue remains the same except for the removal of the first element matching the given element in the queue. I would like to be able to write it this way:

```rust
   spec schema RemovePreburnFromQueueEnsures<CoinType> {
          preburn_address: address;
          amount: u64;
          let preburn_queue = global<PreburnQueue<CoinType>>(preburn_address).preburns;
          let preburn = Preburn { to_burn: Diem { value: amount }};
          let (found, index) = Vector::index_of(preburn_queue, preburn);
          ensures found ==> Vector::eq_remove_elem_at_index(index, preburn_queue, old(preburn_queue));
      }
```

However this is no possible since `Vector::index_of` is impure.

We can express this without using the `index_of` operation using quantification, however this times out due to the nested quantification:
```rust
        let preburn_queue = global<PreburnQueue<CoinType>>(preburn_address).preburns;
          ensures (exists i in 0..len(preburn_queue): preburn_queue[i].to_burn.value == amount &&
                      (forall j in 0..i: preburn_queue[j].to_burn.value != amount) &&
                      (Vector::eq_remove_elem_at_index(i, preburn_queue, old(preburn_queue)))
                  );
```

**Comment by wrwg** [comment]
This is now supported. The syntax is `index_of(vec, e)`.
