### ISSUE TITLE
[Move Prover] Figure out what to do with CVC4 in CI

### ISSUE THREAD

**Issue by DavidLDill** [diem/diem#7665]
# 🚀 Feature Request

We might want to run CVC4 in CI to make sure that it continues to work.  However, we need to clearly mark the source of errors (Z3 vs. CVC4) and manage allow/deny lists differently.

**Comment by wrwg** [comment]
CVC4 is now fully supported in our test infra. It does not run in CI but in nightly together with consistency checks.
