### ISSUE TITLE
Setting up a fullnode in local testnet.

### ISSUE THREAD

**Issue by sm86** [diem/diem#7693]
Waypoints and genesis blob have one on one mapping. Both of them seem necessary for syncing a full node or a validator. They are given as inputs to node-service in yaml file.  

How to create genesis.blob corresponding to the current ledger state?

**Comment by sm86** [comment]
I find that genesis.blob is an optional field for the state sync (public_full_node.yaml comments). Would the synchronization happen if I provide genesis waypoint and the latest waypoint?

**Comment by davidiw** [comment]
Have you seen this: https://developers.diem.com/docs/node/config-deploy-fn/
Here's how our data is generated (with some internal shell script magic or distributed magic if it involves partners): https://github.com/diem/diem/tree/master/config/management/genesis

At a later stage there's something called backup and restore which lacks documentation,  let's send this to @msmouse :) https://github.com/diem/diem/tree/master/storage/backup

**Comment by msmouse** [comment]
@sm86  Can you elaborate your issue? (Like, are you having difficulty trying to bring up a full node to the network? which network?)  

I don't think DB backup and restore tooling is likely in the picture, but https://github.com/diem/diem/blob/master/specifications/db_backup/spec.md this describes the system, and building the db-backup/db-restore CLI tools prints help if you supply no parameters.

**Comment by sm86** [comment]
@msmouse I am running a local testnet and faced issues when I was onboarding a full node. The execution engine fails due to synchronization issues [state root mismatch], so I was looking for alternatives for a faster sync.  
I'll try the backup tool to restore the state.

**Comment by msmouse** [comment]
In that case all you need is the genesis waypoint and genesis blob (genesis means the transaction with version 0 -- the first transaction to set up the basics including the initial validator set), so there is not really a "genesis.blob". 

The backup and restore system can speed up the syncing before we improve the state sync performance, but in a local testnet usually it should not be of your concern.

**Comment by msmouse** [comment]
Btw if you have already messed up the DB by putting in genesis.blob/waypoint copied elsewhere, delete the DB and try again with those copied from a validator. (Good point from @zekun000 )

**Comment by sm86** [comment]
Thanks @msmouse. I'm wondering if I want to start the synchronization from an advanced waypoint, how do I create such a backup?

**Comment by msmouse** [comment]
`db-backup coordinator run local-fs --dir ~/db-backup`  this command continuously backs up to ~/db-backup. 

`db-restore  --target-db-dir ~/db-dir auto  local-fs --dir ~/db-backup` restores all transactions and events plus the latest state snapshot from the backup in `~/db-backup` to `~/db-dir`. 

You can refer to the command line help to learn about options you can pass in.

**Comment by sm86** [comment]
Thank you @msmouse
