### ISSUE TITLE
[Diem Framework Feature Request] Mint v2

### ISSUE THREAD

**Issue by moeziniaf** [diem/diem#7708]
**Context:**
Mint v2 has three principle feature changes: i) tier removal ii) concurrency and iii) attaching metadata/identifier to mints and their events. With mints, TC (Treasury Compliance Account) invokes the contracts and holds resources as opposed to the Designated Dealer (DD) which makes changes a lot more simple (no resource migrations).

**Specifics:**
We want to remove the notion of tiers which are no longer needed in v2.
We also would like to support concurrent mints, which doesn't require any changes in the Diem Framework (only in AOS).
We also would like to attach some metadata to mint transactions, and the event streams (this has been requested by some DDs for easier reconciliation and transaction matching).

The implementation should satisfy the following requirements:

* [ ] Minting takes only an amount `x` along with the currency to be minted, and some optional metadata/identifier.
* [ ] Multiple mint requests in the same currency can be made to the same DD (unchanged)
* [ ] `TierInfo` resource should be removed, and all notions of `Tiers` (Errors, Default tier amounts and tier indexes).
* [ ] Functions related to adding and updating tiers will be removed.
* [ ] ReceivedMintEvent will also take a metadata field (`vector<u8>` type)

As more custom logic is required for mints (open mint windows, future multi-currency limitations, scheduling etc), the rules will  be made by AOS instead of the Diem Framework.

**Comment by dmitri-perelman** [comment]
Thanks @moeziniaf! That matches my understanding as well.
