### ISSUE TITLE
[Feature Request][Faucet] Add Designated Dealer (DD) functionality to the faucet 

### ISSUE THREAD

**Issue by CapCap** [diem/diem#7760]
# 🚀 Feature Request
Add a way to test against a DD in the ecosystem

## Motivation
There is no current way to test against a DD in the current ecosystem. If one existed, it would help onboard and provide a way to verify correct implementation.

## Pitch

**Describe the solution you'd like**

Add additional functionality to the existing rust faucet to add basic DD functionality: 
- Endpoint for agreeing on trade_id's
- Persistent internal state (events, trade_ids, tracked transactions) + API for querying it
- Use CoinTradeMetadata when sending currency (to start, only on-chain transfer without travel rule preflights)
- Accept currency
- Test of aforementioned flows

**Describe alternatives you've considered**
Add the functionality to the diem-python-sdk instead, to complement the ongoing work on the miniwallet, and to in parallel set the ground work for the python sdk becoming the first defacto unified test harness across a wide feature set. There will be a lot of potential duplicate work across the two projects, but it's my understanding that the original faucet was written in python, but was changed to rust.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
aye cap'n

**Comment by bmwill** [comment]
Do we have a spec for what DD interactions look like, off and on-chain, so that we know exactly what functionality is missing from faucet?

**Comment by sunmilee** [comment]
Is this for premainet? or testnet?

**Comment by bmwill** [comment]
> Is this for premainet? or testnet?

I think the intention is for testnet and localnets, but i can see how this would be useful on premainnet as well (to have a test DD) so long as the "faucet" functionality doesn't work since that's reserved for AOS i believe.

**Comment by sunmilee** [comment]
We eventually do want a test DD on premainnet. Doesn't make sense to have a faucet though. If this is just on testnet and localnet then it sounds good, we need to have a separate workstream to host a permanent reference DD on premainnet
