### ISSUE TITLE
[Bug] Move: duplicate definition for BCS

### ISSUE THREAD

**Issue by javaservlets** [diem/diem#7989]
# 🐛 Bug

## To reproduce

Note: this was captured on 2/14/2021

1. follow steps at https://developers.diem.com/docs/move/move-tutorial-creating-coins/
2.  at step '$ move publish src/modules'
==> as seen in attached screenshot, system fails out with 'duplicate definition for BCS'

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
duplicate definition for BCS
// Paste the output here
```

## Expected Behavior

<!-- A clear and concise description of what you expected to happen. -->

## System information

**Please complete the following information:**
- <!-- Diem Version -->
- <!-- Rust Version -->
- <!-- Computer OS -->
macos 11.2.1
<img width="1280" alt="moveError" src="https://user-images.githubusercontent.com/7838889/111819755-f5cc9300-889d-11eb-8f14-d51fe4a673cd.png">


## Additional context

Add any other context about the problem here.

**Comment by bob-wilson** [comment]
When you run `move publish src/modules`, the Move CLI will compile all the Move source files in the `src/modules` directory, and it appears that you somehow got copies of the Move standard library interface files there. The compiler also includes the Move standard library by default, so you're getting 2 copies of all those files (BCS.move and Compare.move show up in the screenshot). My guess is that you previously tried running the command from inside the `src/modules` directory and the tool wrote out the interface files in the `build/mv_interfaces` directory. If you look closely at the steps for the tutorial, you'll see that it says to do `cd toycoin` (i.e., the parent directory of `src/modules`) and the assumption is that you'll run the commands from there. If you remove the `src/modules/build` directory, and then run the command from the `toycoin` directory, it should work.
