### ISSUE TITLE
[Feature Request] Check that the correct version of Boogie is installed when someone runs the prover.

### ISSUE THREAD

**Issue by DavidLDill** [diem/diem#8021]
# 🚀 Feature Request

Check that the correct version of Boogie is installed when someone runs the prover.

## Motivation

If a user fails to upgrade to the correct version of boogie, results can sometimes be mysterious.  Sometimes errors can be missed!  So, when the Move Prover starts up, it would be good to issue a warning if the correct version of Boogie is not running.

For now, we can insist on a specific version (I don't think we need to maintain a set of compatible versions).

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by wrwg** [comment]
This has been fixed a while ago and the prover now prints error messages if Boogie, Z3 or CVC4 have an older version than expected.
