### ISSUE TITLE
A timeout example

### ISSUE THREAD

**Issue by junkil-park** [diem/diem#8034]
The following function `my_withdraw_from` is just wrapping `withdraw_from` in the `DiemAccount` module. `my_withdraw_from` should be functionally equivalent to `withdraw_from` which has been verified. When the function (`my_withdraw_from`) is added to `DiemAccount.move`, it causes a timeout. Although it has no spec, Prover would try to prove the invariants on the function, and hit the timeout. 

```
    fun my_withdraw_from<Token: store>(
        cap: &WithdrawCapability,
        payee: address,
        amount: u64,
        metadata: vector<u8>,
    ): Diem<Token> acquires Balance, AccountOperationsCapability, DiemAccount {
        withdraw_from<Token>(cap, payee, amount, metadata)
    }
```

The error message is as follows:
```
error: verification out of resources/timeout (global timeout set to 40s)

     ┌── DiemAccount.move:564:5 ───
     │
 564 │ ╭     fun my_withdraw_from<Token: store>(
 565 │ │         cap: &WithdrawCapability,
 566 │ │         payee: address,
 567 │ │         amount: u64,
 568 │ │         metadata: vector<u8>,
 569 │ │     ): Diem<Token> acquires Balance, AccountOperationsCapability, DiemAccount {
 570 │ │         withdraw_from<Token>(cap, payee, amount, metadata)
 571 │ │     }
     │ ╰─────^
     │
```

**Comment by emmazzz** [comment]
It seems that the issue is `my_withdraw_from` violates `BalanceNotDecrease` schema in `DiemAccount`. This schema is applied with an except list of functions, and `my_withdraw_from`  should also be added to that list.
