### ISSUE TITLE
[Bug] Restore from backup slows down massively

### ISSUE THREAD

**Issue by mgorven** [diem/diem#8251]
# 🐛 Bug

Testing restore of a 750M transaction chain on `big` testnet. Initially the restore progresses at ~25k TPS, but the speed then drops off significantly.

http://mon.big.aws.hlw3truzy4ls.com/d/storage/storage?orgId=1&from=1619026800000&to=1619031600000
![firefox-20210422-090049](https://user-images.githubusercontent.com/183923/115746613-50e42080-a349-11eb-95b9-35a2fc6cbe31.png)

## System information

**Please complete the following information:**
- 3f7de435

**Comment by mgorven** [comment]
Debugging thread: https://toroeng.slack.com/archives/C01CEC7QGJU/p1619037090018900
Issue does not seem to be caused by EBS, CPU or network throttling. Restarting the restore pod to resume the restore results in the same behaviour of full speed for a while, and then significant slowdown.

**Comment by sherry-x** [comment]
PR for fix: https://github.com/diem/diem/pull/8256
