### ISSUE TITLE
[move-lang] Write set analysis crashes on address values introduced by unpack

### ISSUE THREAD

**Issue by wrwg** [diem/diem#8426]
The new `Vault` hits a bug in the write set analysis. Below the expect crashes:

```
BorrowGlobal(mid, sid, types) => {
   // borrow_global<T>(a). bind ret to a/T
   let addrs = state
        .locals
        .get_local(args[0], func_env)
        .expect("Unbound address local")
        .clone();
     ...
}      
```

The local which is undefined is apparently introduced by unpack, as in `let S{addr} = x; borrow_global_mut<R>(addr)`. In fact, the transfer function rule for Unpack does currently nothing.

To unblock a failing move-cli test for the Vault PR #8396 this code has been made robust in this PR by ignoring the borrow_global_mut if the address local is undefined, and a TODO is added.

**Comment by sblackshear** [comment]
Thanks for flagging! I have a draft PR to handle pack/unpack correctly; will clean it up + submit it soon.
