### ISSUE TITLE
[Feature Request] Add retry to stop sccache 

### ISSUE THREAD

**Issue by sausagee** [diem/diem#8427]
# 🚀 Feature Request

Add retry to stop sccache. 

## Motivation
When x fails to stop the sccache server, it continues.  While this ensures build continues, but it misses out using the remote cache. 
https://github.com/diem/diem/blob/ba0806d8079603ffbc2161a2595d930d3c0f4f8e/devtools/x/src/utils.rs#L70

## Additional context
Ex job in CI, https://github.com/diem/diem/runs/2636608737?check_suite_focus=true

```
    Finished dev [unoptimized + debuginfo] target(s) in 3m 21s
     Running `target/debug/x check -j 16 --members production`
        INFO [06:16:11.999] - sccache of version 0.2.16-alpha.0 is installed
        INFO [06:16:12.021] - Failed to stopped already running sccache.
        WARN [06:16:12.021] - status: exit code: 2
        WARN [06:16:12.022] - stdout: Stopping sccache server...
        WARN [06:16:12.022] - stderr: sccache: error: couldn't connect to server
sccache: caused by: Connection refused (os error 111)
```

**Comment by rexhoffman** [comment]
This just needs a logging improvement, not a retry.
