### ISSUE TITLE
[Bug] Remote logging blocks startup

### ISSUE THREAD

**Issue by mgorven** [diem/diem#8476]
# 🐛 Bug

If the configured remote logging endpoint is not accessible it prevents the node from starting up.

## To reproduce

1. Break logging service
2. Restart node

**Stack trace/error message**
```
 [Logging] Failed to connect: connection timed out
 Failed to send structured log: sending on a full channel
```
[pfn.log.gz](https://github.com/diem/diem/files/6593295/pfn.log.gz)

## Expected Behavior

Node should continue to work if logging is unavailable.

## System information

**Please complete the following information:**
- release-1.3_c3692998

**Comment by gregnazario** [comment]
Note: This doesn't prevent the node from starting up.  The node is running, but this locks up the local logs so it looks like nothing is happening.

The fix here will continue to log at a local logger, at possible decreased retention of sent logs
