### ISSUE TITLE
[bytecode verifier] fix crash bug in bounds checker

### ISSUE THREAD

**Issue by sblackshear** [diem/diem#8500]
## Repro

thread ‘main’ panicked at ‘index out of bounds: the len is 2 but the index is 2’, /home/user/diem-fuzz/diem-main/language/vm/src/access.rs:236:10
stack backtrace:
0: rust_begin_unwind
at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
…
6: vm::access::ScriptAccess::identifier_at at /home/user/diem-fuzz/diem-main/language/vm/src/access.rs:236:10
7: vm::access::ScriptAccess::immediate_dependencies::closure at /home/user/diem-fuzz/diem-main/language/vm/src/access.rs:297:21
…
17: vm::access::ScriptAccess::immediate_dependencies at /home/user/diem-fuzz/diem-main/language/vm/src/access.rs:292:9
18: move_vm_runtime::loader::Loader::deserialize_and_verify_script at /home/user/diem-fuzz/diem-main/language/move-vm/runtime/src/loader.rs:506:28
19: move_vm_runtime::loader::Loader::load_script at /home/user/diem-fuzz/diem-main/language/move-vm/runtime/src/loader.rs:461:21
20: move_vm_runtime::runtime::VMRuntime::execute_script at /home/user/diem-fuzz/diem-main/language/move-vm/runtime/src/runtime.rs:245:13
21: move_vm_runtime::session::Session::execute_script at /home/user/diem-fuzz/diem-main/language/move-vm/runtime/src/session.rs:130:9
…
The input sample is in the github repository https://github.com/suirui17/input_samples_2.git 6.

## Explanation

First, I noticed that the stack backtrace shown here does not match with the input sample available in the Github link.

Second, the input sample in the Github repo does cause a crash (at an access to a SignatureIndex), The reason for the crash is that a CompiledScriptMut is converted to module (say M) first and then applies the bounds checker to M and then convert M back into a CompiledScript .During the process, a dummy signature is added while converting to M and then removed when converting M back to a script. If we refer to Signature index 0 in other parts of the CompiledScriptMut, the bounds checker will not complain (because M does have a dummy signature at index 0) but that dummy signature is subsequently removed, causing subsequent accesses to overflow.

Original conversation [here](https://community.diem.com/t/is-this-a-vulnerability-to-move-vm-3/3600)

**Comment by sblackshear** [comment]
Additional context from an offline discussion: we have killed all code paths that convert a `CompiledScript` into a `CompiledModule` except for this one. The ideal fix would be to fully eliminate these conversions.

**Comment by modocache** [comment]
Using the provided input I've confirmed that #8536 solves this issue -- `move sandbox run input_samples_2.mv` no longer panics, and instead results in `Execution failed with unexpected error CODE_DESERIALIZATION_ERROR`. This error is, I think, the correct one to surface, because the input bytecode is not valid, as it contains parameter data for a signature that does not exist.

This was a great input to test against! I'll have to comment on the original discussion to thank the person who submitted this.
