### ISSUE TITLE
[vm file format] Introduce bytecode operations for `Vector`

### ISSUE THREAD

**Issue by sblackshear** [diem/diem#8502]
`vector`s are a ground type in the Move VM, but all Vector operations are implemented as native functions in the `0x1::Vector` Move module. We should introduce a new bytecode for each of these native functions and get rid of the `Vector` module.

**Comment by sblackshear** [comment]
Tagging @mengxu-fb in case we want to do this by resurrecting the in-progress PR.

**Comment by mengxu-fb** [comment]
`Vector`-related bytecode are added in #6991 for the file format, bytecode verifier, and the IR compiler, and in #8821 for the move VM.
