### ISSUE TITLE
[vm file format] Remove CompiledModuleMut and CompiledScriptMut

### ISSUE THREAD

**Issue by sblackshear** [diem/diem#8506]
These builder types add boilerplate without significant safety wins. E.g., there are many well-formedness checks on scripts and modules that are not enforced by the `*Mut` -> `*` conversion.

The types live [here](https://github.com/diem/diem/blob/main/language/move-binary-format/src/file_format.rs#L1820)

**Comment by bob-wilson** [comment]
This was done in #8667
