### ISSUE TITLE
[move-cli] Only print differences in changed resources during verbose execution

### ISSUE THREAD

**Issue by darioncassel** [diem/diem#8545]
# 🚀 Feature Request

During verbose execution of the Move CLI `sandbox` commands, changes to resources are shown by printing the old version of the resource followed by the new version of the resource. As discussed in #8527, it may be more useful to print out just the parts of the resource that changed rather than printing the entire old and new versions.

## Motivation
The Move CLI `sandbox run` command prints changes to a resource by showing the old and new version of the resource. For example, here the value of a counter changes from 3 to 4:
```
Changed 1 resource(s) under address 0000000000000000000000000A550C18:
    Changed type 0x1::DiemAccount::AccountOperationsCapability: [0, 4, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 85, 12, 24] (wrote 92 bytes)
      Previous:
        key 0x1::DiemAccount::AccountOperationsCapability {
            limits_cap: store 0x1::AccountLimits::AccountLimitMutationCapability {
                dummy_field: false
            }
            creation_events: store 0x1::Event::EventHandle<0x1::DiemAccount::CreateAccountEvent> {
                counter: 3
                guid: 00000000000000000000000000000000000000000a550c18
            }
        }
      New:
        key 0x1::DiemAccount::AccountOperationsCapability {
            limits_cap: store 0x1::AccountLimits::AccountLimitMutationCapability {
                dummy_field: false
            }
            creation_events: store 0x1::Event::EventHandle<0x1::DiemAccount::CreateAccountEvent> {
                counter: 4
                guid: 00000000000000000000000000000000000000000a550c18
            }
        }
```
As pointed out by @metajack, this representation has a lot of redundant information because the *entire* old and new versions of the resource struct get printed out, rather than just the parts that changed.

## Pitch

**Describe the solution you'd like**
This situation can be improved by printing the resource change in the style of a diff:
```
Changed 1 resource(s) under address 0000000000000000000000000A550C18:
    Changed type 0x1::DiemAccount::AccountOperationsCapability: [0, 4, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 85, 12, 24] (wrote 92 bytes)
        key 0x1::DiemAccount::AccountOperationsCapability {
            limits_cap: store 0x1::AccountLimits::AccountLimitMutationCapability {
                dummy_field: false
            }
            creation_events: store 0x1::Event::EventHandle<0x1::DiemAccount::CreateAccountEvent> {
-                counter: 3
+                counter: 4
                guid: 00000000000000000000000000000000000000000a550c18
            }
        }
```
The entire resource is still printed, but now it is only printed once and the difference between its old and new versions is clearly marked.

**Describe alternatives you've considered**
1. To make this even more compact, parts of the resource that did not change can be hidden.
```
Changed 1 resource(s) under address 0000000000000000000000000A550C18:
    Changed type 0x1::DiemAccount::AccountOperationsCapability: [0, 4, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 85, 12, 24] (wrote 92 bytes)
        key 0x1::DiemAccount::AccountOperationsCapability {
        ...
-                counter: 3
+                counter: 4
        ...
        }
```
This approach may have the downside of losing some context unless the entire path to the change is printed, which could be difficult to do with just a textual diff.

2. As suggested by @mengxu-fb, the change to the resource can be printed like a traditional diff. This would also apply to resource creation and deletion (see the discussion in #8527 for examples):
```
  Changed 1 resource(s) under address 0000000000000000000000000A550C18:
    Changed type 0x1::DiemAccount::AccountOperationsCapability: [0, 4, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 85, 12, 24] (wrote 92 bytes)
=        key 0x1::DiemAccount::AccountOperationsCapability {
=            limits_cap: store 0x1::AccountLimits::AccountLimitMutationCapability {
=                dummy_field: false
=            }
=            creation_events: store 0x1::Event::EventHandle<0x1::DiemAccount::CreateAccountEvent> {
-                counter: 3
+                counter: 4
=                guid: 00000000000000000000000000000000000000000a550c18
=            }
=        }
```

A decision on which format is most suitable will require discussion on the intended consumption of this output.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes

## Additional context

N/A

**Comment by modocache** [comment]
It looks like this was resolved in #9752, so I'll close this issue. Nice work! 👍
