### ISSUE TITLE
faucet: simplify API

### ISSUE THREAD

**Issue by bmwill** [diem/diem#8825]
Today there is only a single `/mint` api which does a number of different things. The main use of this api is to create an account + fund that account with a number of coins. Historically account creation wasn't a discrete step that needed to happen so this made sense back then. Today this leads to a couple of problems:
1. Account creation and funding are handled by 2 different transactions from two different accounts, this leads to a race condition if the validators ends up ordering the funding txn before the account creation txn (even though these txns are submitted together as a batch).
2. The mint API requires providing an account's Auth Key and the account address that is used for the fund txn to derived from said auth key. This means it is impossible to request more funds for any account which has rotated its auth key.

In order to address this issue we should introduce 2 two apis `/create` and `/fund` splitting this process into two discrete steps and addressing the api quirks of not being able to request more funds for an account which has rotated its auth key.

**Comment by Grffthjoshua11** [comment]
I’m interested

**Comment by bmwill** [comment]
Awesome! This task can probably be broken into two PRs, implementing `/create` and `/fund` separately. Just let me know if you need any pointers or help.
