### ISSUE TITLE
[Bug] Safety Rules

### ISSUE THREAD

**Issue by gregnazario** [diem/diem#9099]
# 🐛 Bug

Safety rules cannot catchup if waypoint is too out of date.  Waypoint needs to be updated in vault and safety rules needs to be restarted for it to catch up.

## To reproduce

Have a waypoint that is significantly older than the current version for a consensus node.

**Stack trace/error message**
```
[main] INFO consensus/safety-rules/src/safety_rules.rs:328 {"error":"Validator key not found: Data not found in secure storage: Key version not found, key name: diem__consensus, version: XXXXX","event":"error","name":"key_reconciliation"}
```

## Expected Behavior

Either a proper error message telling us it's too old, or it should handle the out of date waypoint appropriately.

## System information

**Please complete the following information:**
- Diem 1.3.2 and earlier

**Comment by gregnazario** [comment]
FYI @davidiw

**Comment by davidiw** [comment]
Going to add a few other considerations here:

1. If the waypoint that we could generate is newer than the stored one, update it. We saw a case where the epoch value was substantially newer than the epoch in the waypoint, which caused the stored waypoint to not be updated:
https://github.com/diem/diem/blob/main/consensus/safety-rules/src/safety_rules.rs#L306-L313
2. Storage only allows pulling a certain amount of epoch proof changes, hence a single iteration of this path may not be sufficient, instead we can create a loop that exits either when the value isn't updated or the epoch is set correctly: https://github.com/diem/diem/blob/main/consensus/src/metrics_safety_rules.rs#L36-L47
3. When starting a new node, safety rules should have a recent waypoint: https://github.com/diem/operator-runbooks/blob/main/blockchain-oncall/adding-validator.md

**Comment by zekun000** [comment]
>  we can create a loop that exits either when the value isn't updated or the epoch is set correctly:

we try to initialize safety rules each time it returns NotInitialized error https://github.com/diem/diem/blob/main/consensus/src/metrics_safety_rules.rs#L50-L63

**Comment by zekun000** [comment]
> We saw a case where the epoch value was substantially newer than the epoch in the waypoint, which caused the stored waypoint to not be updated:

this doesn't sound right, I don't see where we prevent updating substantially new epoch as long as it passes verification.

**Comment by zekun000** [comment]
okay I think this is what happened.

assuming the waypoint was manually updated to an old value. let's say epoch 10, while the safety data is on some newer epoch. let's say epoch 1000.

upon initialize, the proof would only carry epoch 10-110, which is older than 1000 so the epoch value won't get updated. however it'll fail to find the key for epoch 110 since it's too old and fail the initialization.

I guess we could fail more explicitly if the current_epoch is larger than the proof's epoch.
