### ISSUE TITLE
[Bug] State Sync On-chain Configuration Updates

### ISSUE THREAD

**Issue by JoshLind** [diem/diem#9121]
# 🐛 Bug

State sync today is *not* backward compatible if any changes are made to the on-chain configurations that state sync cares about (i.e., this list: https://github.com/diem/diem/blob/main/types/src/on_chain_config/mod.rs#L71). If this list differs from the configs on-chain *at a version* that state sync handles a reconfiguration event, it will panic and the node will be unable to synchronize to the head (where the config list may indeed be correct!).

Example: A node deploys "newer code" (which expects more on-chain configs to exist). But, it starts syncing from genesis (i.e., version 0) where the on-chain configs don't exist. The node will panic, here: https://github.com/diem/diem/blob/20d4d715c9216a892b85455fa64e1389713d4f67/storage/storage-interface/src/lib.rs#L433 (Note: this code is 2 years old and is already on the state sync v2 roadmap to improve, test and fix).

We've only encountered this issue so far in consensus, where @zekun000 has added a new on-chain config (https://github.com/diem/diem/commit/15d785e1c655a0b3c6d638df5ac07674b44fbc0c). However, because the code is buggy, this issue will affect any "new" nodes trying to startup state sync for versions lower than the one that the new config was added on-chain. In some environments, we re-do genesis, so this isn't an issue (genesis automatically initializes the new config values). But for environments where we can't re-do genesis, "new" nodes synchronizing from versions before the initialization point will panic.

Two things need to be fixed:
1. The state sync code should not panic if it cannot find a specific config on-chain at a specific version, but instead log the error and continue to notify its subscribers about the configs that it can provide. In the best case, it'll catch up and there will no longer be a config list mismatch. In the worst case, state sync won't ever be able to provide the value of the config to its reconfiguration subscribers. Which leads to the second issue:
2. Each reconfiguration subscriber needs to be able to handle configs not existing in a reconfiguration notification and react appropriately. For example, if consensus recently added a new config, it needs to be able to handle the case where state sync cannot provide that config value. This is something we want to note going forward: reconfiguration subscribers cannot assume that any new configs they add will be provided in every reconfiguration notification.

**Comment by JoshLind** [comment]
I'll work on a fix for this now on the state sync side. IIUC, (@zekun000), consensus should be able to handle not getting the config values it wants 😄 (I'll also try to check this with a test).

Note: this fix should only need to be hotfixed into environments that: (i) don't re-do genesis; and (ii) expect new nodes to come online that must synchronize using state sync from a version prior to the version where @zekun000 initialized the config values. Given that we're heavily relying on backup and restore today, this hopefully means we should be fine to land this as usual.

**Comment by zekun000** [comment]
> consensus should be able to handle not getting the config values it wants

it's not used and implemented in https://github.com/diem/diem/pull/9111/files (`let onchain_config: OnChainConsensusConfig = payload.get().unwrap_or_default();`)

**Comment by dmitri-perelman** [comment]
Ouch. This whole resource <> Rust interaction is scary. Agree that the right approach is to let the subscribers handle the missing configs (as opposed for the state sync to push them default values). Thanks for digging into this!

**Comment by JoshLind** [comment]
This should now be fixed 😄
