### ISSUE TITLE
[Bug][move prover] Boogie name resolution error on StarCoin code

### ISSUE THREAD

**Issue by sblackshear** [diem/diem#9156]
# 🐛 Bug

Boogie name resolution error when attempting to run the prover on some starcoin code for benchmarking

## To reproduce

See attached repro
[alma_repro.zip](https://github.com/diem/diem/files/7156342/alma_repro.zip)

**Code snippet to reproduce**
```
unzip alma_repro.zip
mvp alma_repro/alma_modules --dependency alma_repro/starcoin_modules
```

**Stack trace/error message**
```
[INFO] running solver
[internal] boogie exited with compilation errors:
output.bpl(12303,49): Error: use of undeclared function: $items#$1_Collection2_Collection'#0'
output.bpl(12303,107): Error: use of undeclared function: $Update'$1_Collection2_Collection'#0''_items
2 name resolution errors detected in output.bpl
```

## System information

Running prover with latest Diem, version d2a6c5c0017cc5edcec82046b8a1baae41378393

**Comment by mengxu-fb** [comment]
This seems to be related to mono analysis not collecting enough information. I'll take a look as well.
