### ISSUE TITLE
[Bug][move-prover] unexpected result on global invariant

### ISSUE THREAD

**Issue by sblackshear** [diem/diem#9167]
# 🐛 Bug

I would expect the prover to report an invariant violation on the following code, but it does not:

```
module 0x1::StructEq {
    struct S { f: u64 }

    invariant forall s: S: s == S { f: 10 };

    public fun new(): S {
        S { f: 11 }
    }
}
```

It's possible that the spec doesn't mean what I think it does. I want to say "all struct `S` values have `f` fields equal to 10. The more idiomatic way to write this is is `spec S { invariant f == 10 }`--the prover does correctly flag this as violated for the above code). I wrote the invariant in this funky way as a stress-test for the escape analysis, which tries to determine if leaked mutable references to fields are relevant to the module's specs.

**Comment by mengxu-fb** [comment]
This is interesting and highlighted what @DavidLDill has been suggesting to me for a while: producing a warning for global invariants that are not instrumented anywhere in the program.

What actually happened in this case is that, we instrument global invariants on bytecode instructions that have memory operations (e.g., move_from, move_to, write_back), and this global invariant
`invariant forall s: S: s == S { f: 10 };`
does not involve the global memory and hence, are not instrumented anywhere in the program.

**Comment by wrwg** [comment]
The invariant on module level is a global memory invariant. It will be only evaluated on memory updates. (We were planning to mark dead invariants with warnings.) To make a struct data invariant, use

```
spec S { invariant f == 10; }
```

**Comment by mengxu-fb** [comment]
@wrwg @DavidLDill an alternative (or rather, beyond reporting unused invariants) is to reject global invariants that has no mentioning of the global state.

**Comment by wrwg** [comment]
On Tue, Sep 14, 2021 at 9:19 AM Meng Xu ***@***.***> wrote:

> @wrwg <https://github.com/wrwg> @DavidLDill
> <https://github.com/DavidLDill> an alternative (or rather, beyond
> reporting unused invariants) is to reject global invariants that has no
> mentioning of the global state.
>

That is less general than reporting dead invariants.
