### ISSUE TITLE
[move package][bug] crash on second run of `move package test` when there's a failing test

### ISSUE THREAD

**Issue by sblackshear** [diem/diem#9441]
If you run `move package test` on a package with a failing test, it succeeds the first time (correctly shows the failing test), but the second run leads to a crash.

To repro:
```
cd diem/language/move-stdlib
// add a failing test under tests
move package test // works
move package test
CACHED MoveStdlib
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', language/tools/move-cli/src/package/cli.rs:227:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by tzakian** [comment]
Should be fixed by #9491 There was a caching issue when running tests where we were pulling in the cached compilation artifacts for the root package when in reality we need to recompile it to build the test plan.
