### ISSUE TITLE
[move-cli] Update CLI README with package commands

### ISSUE THREAD

**Issue by sblackshear** [diem/diem#9507]
The CLI Readme is probably out-of-date in a number of ways, but one particularly important one is that `move package` commands aren't documented. These commands are only described in the [changelog](https://github.com/diem/diem/blob/main/language/changes/7-packages.md), which is not the most discoverable.

**Comment by modocache** [comment]
Thanks for pointing this out! I think #9871 did a great job of resolving this issue. Please re-open this if you feel there's anything lacking!
