### ISSUE TITLE
[move package manager][Bug] Move package manager fails to resolve git dependency on Move stdlib

### ISSUE THREAD

**Issue by sblackshear** [diem/diem#9590]
If I create a new Move package with this Move.toml

```
[package]
name = "TestProject"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/diem/diem/language/move-stdlib", rev = "8fab7b7f2e131bdcfad475b0509c636e5e1883bf" }

[addresses]
Std = "_"

[dev-addresses]
Std = "0x1"
```

, I get an error when running `move package build`:

```
Error: Unable to resolve packages for package 'TestProject'

Caused by:
    0: While resolving dependency 'MoveStdlib' in package 'TestProject'
    1: While processing dependency 'MoveStdlib'
    2: Unable to find package manifest for 'MoveStdlib' at "/Users/shb/.move/https___github_com_diem_language_move-stdlib_8fab7b7f2e131bdcfad475b0509c636e5e1883bf/"
```

It's possible that I'm using the git dependency syntax incorrectly, but I can't find it documented [here](https://github.com/diem/diem/blob/main/language/changes/7-packages.md) or elsewhere, so I'm not sure.

**Comment by sblackshear** [comment]
@tzakian: do you have a sense of what the issue might be here? I'm happy to take a crack at fixing it if you can point me in the right direction.

**Comment by tzakian** [comment]
Ah! Sorry about not seeing this sooner. The issue here is you can't pass a full git url with subdir to the `git` field and have that work. Additionally, you need to pass the "git clone" url to the `git` field. 

So in order to do the equivalent of what you have above you would need to do the following (and this should work!):

```
[package]
name = "TestProject"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/diem/diem.git" subdir = "language/move-stdlib", rev = "8fab7b7f2e131bdcfad475b0509c636e5e1883bf" }

[addresses]
Std = "_"

[dev-addresses]
Std = "0x1"
```

If that doesn't work, it's definitely a bug :)

**Comment by sblackshear** [comment]
Thank you Tim, that did it for me! I put up https://github.com/diem/diem/pull/9842 to document this.
