### ISSUE TITLE
top readme on diem:diem has broken links to developers.diem.com [Bug]

### ISSUE THREAD

**Issue by dahliamalkhi** [diem/diem#9803]
# 🐛 Bug

If you're looking to report an issue with the Diem Core project go to https://github.com/diem/diem

the readme displayed at top page on diem/diem has several broken links to developers.diem.com 

## Steps to reproduce

go to https://github.com/diem/diem

press links under "getting started" 

** Error message or problem **
```
// page not found
```

## Expected Behavior

Fix the links

## System information

**Please complete the following information:**
-

**Comment by bob-wilson** [comment]
The broken links are:

- Diem Protocol: Key Concepts (https://developers.diem.com/docs/core/diem-protocol): not sure what this used to be; it looks like the closest thing we have now is the start of the "Basics" section (https://developers.diem.com/docs/basics/basics-txns-states)
- Life of a Transaction (https://developers.diem.com/docs/core/life-of-a-transaction): should be https://developers.diem.com/docs/transactions/basics-life-of-txn
- My First Transaction (https://developers.diem.com/docs/core/my-first-transaction): should be https://developers.diem.com/docs/tutorials/tutorial-my-first-transaction
- Getting Started With Move (https://developers.diem.com/docs/move/move-introduction): should be https://diem.github.io/move/introduction.html
